[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "parser"
path = "src/bin/parser.rs"  # Cargo will find it here automatically, but good to be explicit
test = false
bench = false

[dependencies]
ollama-rs = "0.3.4"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
